### ISSUE TITLE
What is this? :)

### ISSUE THREAD

**Issue by sgdc3** [MCCarbon/DecompileTools#1]

**Comment by Shevchik** [comment]
Tools used for Carbon devepment.
Allows us to start with ~500 class names and all enum constants deobfuscated.

**Comment by sgdc3** [comment]
Wow, can you tell something about carbon?

**Comment by Shevchik** [comment]
We are currently improving our tools and deobfuscating server to inspect changes.

**Comment by wgaylord** [comment]
Is this project dead?

**Comment by Shevchik** [comment]
Kinda, don't have time to work on carbon tight now.
